name: Update Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Full-year calendar SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: America/Mexico_City 

      - name: Generate Recent Activity Charts SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes 
          config_timezone: America/Mexico_City

      - name: Commit generated SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar métricas (isocalendar y habits)"
          file_pattern: metrics.plugin.isocalendar.fullyear.svg metrics.plugin.habits.charts.svg
          # file_pattern: *.svg
